const projects = [
  {
    id: 1,
    name: 'Corona Info Tracker',
    img: './images/corona-app.png',
    company: 'Personal',
    dot: './images/dot.svg',
    position: 'Front-End-Dev',
    date: '2022',
    description: 'This app  allows users to get get information of Covid-19 disease from all over the world. built with React, Redux, and JavaScript.',
    tech1: 'React',
    tech2: 'Redux',
    tech3: 'API',
    modalclose: './images/Enabled-3.svg',
    liveLink: 'https://cheery-concha-41a565.netlify.app',
    sourceLink: 'https://github.com/Shubh-Dev/corona-info-tracker',
    seeLive: './images/Icon-export-button.svg',
    seeSource: './images/github.svg',
  },
  {
    id: 2,
    name: 'Math-Magicians',
    img: './images/math-magician.png',
    company: 'Personal',
    dot: './images/dot.svg',
    position: 'Front-End-Dev',
    date: '2022',
    description: 'The website allows math lovers to play with numbers. Built with React, JavaScript, and CSS.',
    tech1: 'React',
    tech2: 'JavaScript',
    tech3: 'CSS',
    modalclose: './images/Enabled-3.svg',
    liveLink: 'https://fast-anchorage-14363.herokuapp.com/calculator',
    sourceLink: 'https://github.com/Shubh-Dev/math-magician-react',
    seeLive: './images/Icon-export-button.svg',
    seeSource: './images/github.svg',
  },
  {
    id: 3,
    name: 'Leaderboard',
    img: './images/leaderboard.png',
    company: 'Personal',
    dot: './images/dot.svg',
    position: 'Front-End-Dev',
    date: '2022',
    description: 'Leaderboard is a tool that helps to keep records of game scores. It simply lists the names and corresponding scores. Built with JavaScript, webpack, CSS.',
    tech1: 'JavaScript',
    tech2: 'Webpack',
    tech3: 'CSS',
    modalclose: './images/Enabled-3.svg',
    liveLink: 'https://cheery-caramel-b70a4d.netlify.app/',
    sourceLink: 'https://github.com/Shubh-Dev/LeaderBoard',
    seeLive: './images/Icon-export-button.svg',
    seeSource: './images/github.svg',
  },
  {
    id: 4,
    name: 'Space Travelers Hub',
    img: './images/space-traveller.png',
    company: 'Personal',
    dot: './images/dot.svg',
    position: 'Front-End-Dev',
    date: '2022',
    description: 'This is react app that allows users to book missions and reserve rockets. Built with React, Redux, API, and CSS.',
    tech1: 'React',
    tech2: 'Redux',
    tech3: 'API',
    modalclose: './images/Enabled-3.svg',
    liveLink: 'https://travelers-hub-rich-shubh.netlify.app/',
    sourceLink: 'https://github.com/assadounto/space-x',
    seeLive: './images/Icon-export-button.svg',
    seeSource: './images/github.svg',
  },
];

export default projects;